### ISSUE TITLE
'System seems singular' and 'EM algorithm failed' for Mixture Markov Model

### ISSUE THREAD

**Issue by dyisaev** [helske/seqHMM#56] opened 2021-05-21 13:05 UTC
I am trying to use seqHMM to fit a Mixture Markov Model with 2 clusters.

I get multiple warnings:

```warning: solve(): system seems singular; attempting approx solution```

```EM algorithm failed: Estimation of gamma coefficients failed due to non-finite cluster probabilities. 4:In fit_model(mod, global_step = TRUE, local_step = TRUE, control_em = list(restart = list(times = 10))) ```

here's the code and data for reproducible example:
```
library(seqHMM)
data=read.csv2('sequences.csv')

data.labels = c("S0","S1","S2","S3")
data.seq = seqdef(data,labels=data.labels)
set.seed(1234)

mod<-build_mmm(data.seq, n_clusters=2)

fit<-fit_model(mod,                    
                global_step=TRUE,     # additional arguments for the optimizier
                local_step=TRUE,      # to avoid local maximum
                control_em=list(restart = list(times=10)))
```

here's the data file:
[sequences.csv](https://duke.box.com/s/mfhk0vdryay7ff1ri1hcuwhsm9rdsslo)

I'd greatly appreciate help to make it work.

**Comment by helske** [comment] 2021-05-24 05:04
The warning is from the EM algorithm phase where mixture probabilities are optimized. Sometimes this warning is due to high collinearity in the covariates, but here in the intercept-only model, the issue is likely due to the fact that the algorithm sometimes finds an optimum where all the sequences are assigned to a single cluster, which can break things. For example, without an EM algorithm I get this:

```
fit1<-fit_model(mod,                    
    global_step=TRUE,  
    local_step=TRUE,
    em_step = FALSE)

summary(fit1$model)
Covariate effects :
Cluster 1 is the reference.

Cluster 2 :
             Estimate  Std. error
(Intercept)      17.8         818   ## See very large intercept, leading to

Log-likelihood: -15683.93   BIC: 31676.59 

Means of prior cluster probabilities :
Cluster 1 Cluster 2 
 1.92e-08  1.00e+00   ## Everyone is assigned to second cluster

Most probable clusters :
            Cluster 1  Cluster 2
count               0         78
proportion          0          1

Classification table :
Mean cluster probabilities (in columns) by the most probable cluster (rows)

          Cluster 1 Cluster 2
Cluster 1       NaN       NaN
Cluster 2         0         1
```
But actually running EM algorithm once gives another solution with better log-likelihood, it's then the subsequent restarts that fail. What you could try is to set better initial values when constructing the model (with arguments `transition_probs` etc), or you could tweak the randomization of repeated EM algorithm, ie. `control_em=list(restart = list(times=10, sd = 0.1)`. 

On the other hand, this is just a warning that some of the restarts did not work properly, but some of them do work as can be seen from the vector of obtained log-likelihoods:
```
fit$em_results$best_opt_restart
 [1] -15571.72 -15571.72 -15579.59 -15683.93 -15683.93 -15683.93
 [7] -17374.90 -18313.22      -Inf      -Inf      -Inf
```

**Comment by dyisaev** [comment] 2021-05-24 23:59
Thank you for replying, indeed setting `sd` parameter for EM randomization did the trick.

Thanks!

**Closed** 2021-06-17 12:43 UTC
