### ISSUE TITLE
Error: number of labels must equal number of states in the alphabet

### ISSUE THREAD

**Issue by loxavia** [helske/seqHMM#68] opened 2023-04-05 05:47 UTC
I am getting this error on plots that were perfectly plotting before and that seems to happen with different versions of the package and different R installations.

mssplot(mhmm_fit_3cl$model, plots = "both", type = "I", sortv = "mds.hidden")

Error: 
[!] number of labels must equal number of states in the alphabet

**Comment by helske** [comment] 2023-04-05 06:29
This might be due to some recent changes in `TraMineR`, but it's bit difficult to know the exact cause of the error as for example `mssplot(mhmm_biofam, plots = "both", type = "I", sortv = "mds.hidden")` does not throw errors on my end. Can you provide reproducible example?

**Comment by loxavia** [comment] 2023-04-05 07:21
Thank you for the rapid response, I can send it privately, since the data can't be shared publicly,
Here is my email mohammed.saqr@uef.fi   if you don't want to share the email here.

**Comment by helske** [comment] 2023-04-05 08:48
Thanks, you can send it to jouni.helske@iki.fi.

**Comment by helske** [comment] 2023-04-05 17:26
The issue was due to changes in `hidden_paths` which now respects void symbols by default (see https://github.com/helske/seqHMM/issues/58), but `mssplot` failed with the default `respect_void = TRUE`. I just pushed a fix which seems to work at least in your example. Let me know if you encounter further problems.

**Closed by helske** 2023-04-05 17:26 UTC
